# Docker file to run and test the image locally
# make change in appy.py - if __name__ == "__main__":
#app.run(host="0.0.0.0", port=5000)

#Use the Python 3.9 image
FROM python:3.9-slim

# Install any needed packages
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY app.py .

# Expose the port Flask will run on
EXPOSE 5000

# Set the default command to run the Flask app
CMD ["python", "app.py"]

